version: '3.4'

services:
  java-app:
    image: 'erdem/reading-is-good'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - mongodb
  mongodb:
    container_name: mongodb
    hostname: mongodb
    image: 'mongo:4.4'
    ports:
      - '27017:27017'
    volumes:
      - 'mongodb_data:/data/db'
      - 'mongodb_config:/data/configdb'
    environment:
      - MONGO_INITDB_DATABASE=reading-is-good
      - MONGO_REPLICA_SET_NAME=rs0
    healthcheck:
      test: test $$(echo "rs.initiate().ok || rs.status().ok" | mongo --quiet) -eq 1
      interval: 10s
      start_period: 30s
    command: [ "--replSet", "rs0", "--bind_ip_all" ]
volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local